spring: 
  config: 
    activate: 
      #프로파일 활성화시 사용할 속성을 정의 
      on-profile: local 
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kscjje?autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&characterEncoding=UTF-8
    username: kscjje
    password: dlscjs12!@
